---
title: "flags"
output: github_document
---

+-----+--------------------------+-------------------------------------------------------------------------------+
| \#  | Variable                 | Label                                                                         |
+=====+==========================+===============================================================================+
| 1   | DESY_SORT_KEY            | LDS                                                                           |
|     |                          | Beneficiary ID                                                                |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 2   | npi                      | Claim                                                                         |
|     |                          | Attending Physician NPI Number                                                |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 3   | clm_dt                   | Claim                                                                         |
|     |                          | Admission Date                                                                |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 4   | DOB_DT                   | LDS                                                                           |
|     |                          | Age Category                                                                  |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 5   | GNDR_CD                  | Gender                                                                        |
|     |                          | Code from Claim                                                               |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 6   | BENE_RACE_CD             | Race                                                                          |
|     |                          | Code from Claim                                                               |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 7   | psa                      | HCPCS:                                                                        |
|     |                          | PSA test                                                                      |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 8   | cerv                     | HCPCS:                                                                        |
|     |                          | cervical cancer screening                                                     |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 9   | crc                      | HCPCS:                                                                        |
|     |                          | colon cancer screening, sigmoidoscopy, colonoscopy, barium enemaor blood      |
|     |                          | occult test                                                                   |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 10  | canscrn                  | HCPCS:                                                                        |
|     |                          | breast, cervix, colon, or prostate cancer screening                           |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 11  | crc_dx                   | ICD:                                                                          |
|     |                          | condition for crc                                                             |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 12  | canscrn_dx               | ICD:                                                                          |
|     |                          | breast, cervix, colon, or prostate cancer screening                           |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 13  | dialysis_dx              | ICD:                                                                          |
|     |                          | dialysis                                                                      |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 14  | prostate_dx              | ICD:                                                                          |
|     |                          | prostate cancer, elevated PSA, or family history of prostate cancer           |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 15  | cerv_ex                  | ICD:                                                                          |
|     |                          | High risk for cervical cancer screening                                       |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 16  | dialysis                 | dialysis                                                                      |
|     |                          | (dialysis_dx or dialysis_betos)                                               |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 17  | hypercoagula             | HCPCS:                                                                        |
|     |                          | hypercoagulability test                                                       |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 18  | embolism_dx              | ICD:                                                                          |
|     |                          | pulmonary embolism or venous embolism with thrombosis                         |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 19  | t3                       | HCPCS:                                                                        |
|     |                          | total or free T3 testing                                                      |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 20  | hypothyroidism_dx        | ICD:                                                                          |
|     |                          | hypothyroidism                                                                |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 21  | bonemd_cpt               | HCPCS:                                                                        |
|     |                          | bone mineral density test                                                     |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 22  | dxa_dx                   | ICD:                                                                          |
|     |                          | dual-energy x-ray absorptiometry (DXA)                                        |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 23  | bonemd                   | Bone                                                                          |
|     |                          | mineral density test or dual-energy x-ray absorptiometry (bonemd_cpt or       |
|     |                          | dxa_dx)                                                                       |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 24  | fracture_cpt             | HCPCS:                                                                        |
|     |                          | fragility fracture                                                            |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 25  | cancer_dx                | ICD:                                                                          |
|     |                          | cancer                                                                        |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 26  | fracture_dx              | ICD:                                                                          |
|     |                          | fragility fracture                                                            |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 27  | osteoporosis_dx          | ICD:                                                                          |
|     |                          | osteoporosis                                                                  |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 28  | fracture                 | fragility                                                                     |
|     |                          | fracture (fracture_cpt or fracture_dx)                                        |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 29  | vitaminD_cpt             | HCPCS:                                                                        |
|     |                          | vitamin D test                                                                |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 30  | chronic_dx               | ICD:                                                                          |
|     |                          | chronic conditions for vitaminD test                                          |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 31  | other_risk_dx            | ICD:                                                                          |
|     |                          | other risk factors for vitaminD test                                          |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 32  | pregnancy_obesity_dx     | ICD:                                                                          |
|     |                          | pregnancy/obesity condition for vitaminD test                                 |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 33  | imglbp                   | HCPCS:                                                                        |
|     |                          | imaging of the lower back                                                     |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 34  | imglbp_inc_dx            | ICD:                                                                          |
|     |                          | lower back pain                                                               |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 35  | imglbp_exc_dx            | ICD:                                                                          |
|     |                          | known possible cause for lower back pain                                      |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 36  | crc_cancer_dx            | ICD:                                                                          |
|     |                          | colorectal cancer                                                             |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 37  | dialysis_betos           | BETOS:                                                                        |
|     |                          | dialysis                                                                      |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 38  | xray                     | HCPCS:                                                                        |
|     |                          | chest x-ray                                                                   |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 39  | emergencycare            | HCPCS:                                                                        |
|     |                          | emergency care                                                                |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 40  | low_risk_noncard_betos   | BETOS:                                                                        |
|     |                          | low or intermediate risk non-cardiothoracic surgical procedure                |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 41  | low_risk_noncard_cpt     | HCPCS:                                                                        |
|     |                          | low or intermediate risk non-cardiothoracic surgical procedure                |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 42  | low_risk_noncard         | low or                                                                        |
|     |                          | intermediate risk non-cardiothoracic surgical procedure (low_risk_noncard_cpt |
|     |                          | or low_risk_noncard_betos)                                                    |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 43  | fracture_vd_dx           | ICD:                                                                          |
|     |                          | fragility fracture, used in labeling LVC for VitaminD test                    |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 44  | fracture_vd              | fragility                                                                     |
|     |                          | fracture (fracture_cpt or fracture_vd_dx), used in labelling LVC for vitaminD |
|     |                          | test                                                                          |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 45  | echocardiogram           | HCPCS:                                                                        |
|     |                          | echocardiogram                                                                |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 46  | pulmonary                | HCPCS:                                                                        |
|     |                          | pulmonary function test (PFT)                                                 |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 47  | eenc                     | HCPCS:                                                                        |
|     |                          | electrocardiogram, echocardiogram, nuclear medicine imaging, cardiac MRI or   |
|     |                          | CT angiography                                                                |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 48  | maxillofacialCT          | HCPCS:                                                                        |
|     |                          | CT of maxillofacial area                                                      |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 49  | sinusitis_dx             | ICD:                                                                          |
|     |                          | sinusitis                                                                     |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 50  | other_related_comp_dx    | ICD:                                                                          |
|     |                          | other related complications for algorithm 14                                  |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 51  | headimg                  | HCPCS:                                                                        |
|     |                          | CT or MRI of head or brain                                                    |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 52  | syncope_dx               | ICD:                                                                          |
|     |                          | syncope                                                                       |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 53  | warranted_img_dx         | ICD:                                                                          |
|     |                          | warranted imaging: epilepsy or convulsions, cerebrovacular diseases including |
|     |                          | stroke/TIA and subarachnoid hemorrhage, head or face trauma, altered mental   |
|     |                          | status, nervous and musculoskeletal system symptoms including gait            |
|     |                          | abnormality, meningismus. disturbed skin sensation and speech deficits,       |
|     |                          | personal history of stroke/TIA                                                |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 54  | headache_dx              | ICD:                                                                          |
|     |                          | diagnoses for headache                                                        |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 55  | warranted_img2_dx        | ICD:                                                                          |
|     |                          | warranted imaging: post-tramatic or thunderclap headache, cancer, migraine    |
|     |                          | with hemiplegia or infarction, giant cell arteritis, epilepsy or convulsions, |
|     |                          | cerebrovascular diseases including stroke/TIA and subarachnoid hemorrhage,    |
|     |                          | head or face trauma, altered mental status, nervous and musculoskeletal       |
|     |                          | system symptoms including gait abnormality, meningismus, disturbed skin       |
|     |                          | sensation and speech deficits, personal history of stroke/TIA or cancer       |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 56  | eeg                      | HCPCS:                                                                        |
|     |                          | electroencephalogram (EEG)                                                    |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 57  | eeg_headache_dx          | ICD:                                                                          |
|     |                          | headache, asoociated with EEG LVC labeling                                    |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 58  | epilepsy_dx              | ICD:                                                                          |
|     |                          | epilepsy or convulsions                                                       |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 59  | carotid                  | HCPCS:                                                                        |
|     |                          | carotid imaging                                                               |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 60  | stroke_etc_dx            | ICD:                                                                          |
|     |                          | stroke/TIA, retinal vascular occlusion/ischemia, or nervous and               |
|     |                          | musculoskeletal symptoms, asoociated with carotic LVC labeling                |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 61  | neurologic_dx            | ICD:                                                                          |
|     |                          | other neurologic symptoms: stroke or TIA, history of stroke or TIA, retinal   |
|     |                          | vascular occlusion or ischemia, or nervous or musculoskeletal symptoms        |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 62  | radiographic             | HCPCS:                                                                        |
|     |                          | radiographic imaging: foot radiograph, foot MRI, or extemity ultrasound       |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 63  | plantarfasciitis_dx      | ICD:                                                                          |
|     |                          | plantar faciitis                                                              |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 64  | footpain_dx              | ICD:                                                                          |
|     |                          | foot pain                                                                     |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 65  | stress                   | HCPCS:                                                                        |
|     |                          | stress testing, cardiac MRI, CT angiography                                   |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 66  | ischemic_dx              | ICD:                                                                          |
|     |                          | ischemic heart disease or acute myocardial infarction diagnosis               |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 67  | endarterectomy           | HCPCS:                                                                        |
|     |                          | carotid endarterectomy                                                        |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 68  | stroketia_dx             | ICD:                                                                          |
|     |                          | stroke or TIA, stroke or TIA, or focal neurological symptoms                  |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 69  | homocysteine             | HCPCS:                                                                        |
|     |                          | homocysteine testing                                                          |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 70  | folate_dx                | ICD:                                                                          |
|     |                          | folate or B12 deficiencies                                                    |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 71  | pth                      | HCPCS:                                                                        |
|     |                          | parathyroid hormone (PTH) measurement                                         |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 72  | kidney_dx                | ICD:                                                                          |
|     |                          | chronic kidney disease                                                        |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 73  | hypercalcemia_dx         | ICD:                                                                          |
|     |                          | hypercalcemia diagnosis                                                       |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 74  | pci                      | HCPCS:                                                                        |
|     |                          | percutaneous coronary intervention (PCI)                                      |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 75  | stablecoronary_dx        | ICD:                                                                          |
|     |                          | stable coronary disease (defined as ischemic heart disease or acute           |
|     |                          | myocardial infarction                                                         |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 76  | angina_dx                | ICD:                                                                          |
|     |                          | unstable angina or myocardial infarction                                      |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 77  | angioplasty              | HCPCS:                                                                        |
|     |                          | renal/visceral angioplasty or stent placement                                 |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 78  | atherosclerosis_dx       | ICD:                                                                          |
|     |                          | renal atherosclerosis or renovascular hypertension                            |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 79  | fibromuscular_dx         | ICD:                                                                          |
|     |                          | fibromuscular dysplasia                                                       |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 80  | ivc                      | HCPCS:                                                                        |
|     |                          | inferior vena cava (IVC) placement                                            |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 81  | thrombosis_dx            | ICD:                                                                          |
|     |                          | pulmonary embolism or deep vein thrombosis                                    |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 82  | catheterization          | HCPCS:                                                                        |
|     |                          | pulmonary artery catheterization (Swan-Ganz replacement)                      |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 83  | pulmonaryhypertension_dx | ICD:                                                                          |
|     |                          | pulmonary hypertension or cardiac tamponade                                   |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 84  | surgical_drg             | DRG:                                                                          |
|     |                          | surgical MS-DRG                                                               |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 85  | verte                    | HCPCS:                                                                        |
|     |                          | vertebroplasty or kyphoplasty                                                 |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 86  | vertebralfracture_dx     | ICD:                                                                          |
|     |                          | vertebral fractures                                                           |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 87  | bonecancer_dx            | ICD:                                                                          |
|     |                          | bone cancer, myeloma, hemongioma                                              |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 88  | knee                     | HCPCS:                                                                        |
|     |                          | arthroscopic debridement/ chondroplasty of the knee                           |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 89  | osteoarthritis_dx        | ICD:                                                                          |
|     |                          | osteoarthritis or chondromalacia                                              |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 90  | meniscaltear_dx          | ICD:                                                                          |
|     |                          | meniscal tears                                                                |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 91  | inject                   | HCPCS:                                                                        |
|     |                          | epidural, facet, or trigger point injections                                  |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 92  | etanercept               | HCPCS:                                                                        |
|     |                          | etanercept injection                                                          |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 93  | lowbackpain_dx           | ICD:                                                                          |
|     |                          | lower back pain                                                               |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 94  | radiculopathy_dx         | ICD:                                                                          |
|     |                          | radiculopathy                                                                 |
+-----+--------------------------+-------------------------------------------------------------------------------+
| 95  | SRC                      | Source                                                                        |
|     |                          | of claim, CR (Carrier) IP(Inpatient) OP(Outpatient)                           |
+-----+--------------------------+-------------------------------------------------------------------------------+
